DEFAULT_PARENT_FOLDER = '.exprec'
METADATA_JSON_FILENAME = 'experiment.json'
FILES_FOLDER = 'files'
ARCHIVE_TAG = 'archive'
SOURCE_CODE_FOLDER = 'src'
SCALARS_FOLDER = 'scalars'
SCALARS_HEADER_FIELDS = ['step', 'value', 'datetime']
IMAGE_FOLDER = 'img'
TAG_REGEX_PATTERN = '^[a-z0-9-]*$'
